# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
kotlin.daemon.jvm.options=-Xmx2048m
kotlin.code.style=official
android.useAndroidX=true
android.nonFinalResIds=false
android.suppressUnsupportedCompileSdk=35
kotlin.suppressKotlinVersionCompatibilityCheck=true
ksp.incremental=false
kotlin.incremental=false
kotlin.jvm.target.validation.mode=IGNORE